name    'puppetlabs-gce_compute'
version '0.1.0'
source  'https://github.com/puppetlabs/puppetlabs-gce_compute'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs GCE Module'
description 'GCE Module for Puppet using gcutil-1.8.3'
project_page 'https://github.com/puppetlabs/puppetlabs-gce_compute'
